project_name: mcp-skill-cli

builds:
  - id: mcp
    main: ./cmd/mcp
    binary: mcp
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: skill
    main: ./cmd/skill
    binary: skill
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: mcp
    builds:
      - mcp
    format: binary
    name_template: "mcp_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if eq .Os \"windows\" }}.exe{{ end }}"
  - id: skill
    builds:
      - skill
    format: binary
    name_template: "skill_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if eq .Os \"windows\" }}.exe{{ end }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
